name: pulumaz
description: A minimal Azure Native TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
    nodeargs: --max-old-space-size=4096
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
