name: pulumaz
description: A minimal Azure Native TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
    # This fixed an issue with github actions erroring example: https://github.com/jrizo0/pulumaz/actions/runs/12507306441/job/34893613129
    nodeargs: --max-old-space-size=4096
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
