name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Setup pulumi-azure environment
      #   run: |
      #     export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.clientId')
      #     export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r '.clientSecret')
      #     export ARM_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r '.subscriptionId')
      #     export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.tenantId')

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      - name: Run pnpm install
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: dev
          work-dir: ./infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
