name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      swa_name: ${{ steps.pulumi_out.outputs.swa_name }}
      deploy_token: ${{ steps.azure_cli.outputs.deploy_token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Pulumi outputs
        id: pulumi_out
        run: |
          cd infra
          pulumi stack select dev
          echo "swa_name=$(pulumi stack output swa_name)" >> $GITHUB_OUTPUT
        env: 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        id: azure_cli
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "deploy_token=$(az staticwebapp secrets list --name ${{ steps.pulumi_out.outputs.swa_name }} -o json | jq -r .properties.apiKey)" >> $GITHUB_OUTPUT

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: variables
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ needs.variables.outputs.deploy_token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "packages/www/" # App source code path
          output_location: ".next" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    # skip remove env for 'dev' branch
    if: >
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.base.ref != 'dev'
    needs: variables
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ needs.variables.outputs.deploy_token }}
